---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: daniellavoie/puppeteer
    tag: 8-stretch

inputs:
- name: src
- name: src-ci
- name: app-url

run:
  path: src-ci/ci/tasks/frontend-acceptance-tests/frontend-acceptance-tests.sh
  
params:
  PROFILE: 