---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: daniellavoie/cf-cli
    tag: alpine

inputs:
- name: build
- name: config
- name: src-ci

outputs:
- name: cf-space
- name: app-url

run:
  path: src-ci/ci/tasks/push-to-cf/push-to-cf.sh

params:
  APP_NAME:
  APP_HOSTNAME:
  APP_DOMAIN:
  DB_NAME:
  DB_SERVICE_NAME:
  DB_SERVICE_PLAN:
  BUILDPACK:
  CF_API:
  CF_USER:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
  CF_SPACE_PREFIX:
  CF_PATH:
  
  