---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk-slim

inputs:
- name: ci
- name: src

outputs:
- name: build

run:
  path: ci/ci/tasks/maven-package/maven-package.sh