---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: src-pr
  type: pull-request
  source:
    repo: {{github-repository}}
    access_token: {{github-access_token}}

- name: src-master
  type: git
  source:
    uri: {{git-master-uri}}
    branch: master

- name: config-pr
  type: git
  source:
    uri: {{git-config-uri}}
    branch: pr-config

- name: config-staging
  type: git
  source:
    uri: {{git-config-uri}}
    branch: staging-config

- name: config-production
  type: git
  source:
    uri: {{git-config-uri}}
    branch: prod-config
    
- name: artifacts
  type: s3
  source:
    bucket: spring-boot-sample-blockchain-artifacts
    versioned_file: spring-boot-sample-blockchain.jar
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-access-secret}}
    region_name: {{s3-region-name}}

- name: docker-image-spring-boot-sample-blockchain
  type: docker-image
  source:
    username: {{blockchain-registry-username}}
    password: {{blockchain-registry-password}}
    repository: registry.blockchain.cf-demo.com/daniellavoie/spring-boot-sample-blockchain
    
- name: app-url
  type: s3
  source:
    bucket: spring-boot-sample-blockchain-artifacts
    versioned_file: app-url
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-access-secret}}
    region_name: {{s3-region-name}}
    
jobs:
- name: validate-pull-request
  plan:
  - get: config-pr
  - get: src-pr
    trigger: true
  - task: build
    file: src-pr/ci/tasks/maven-package/maven-package.yml
    input_mapping:
      src: src-pr
      src-ci: src-pr
    params:
      TARGET_PATH: src/backend/target/*
  - task: push-to-cf
    file: src-pr/ci/tasks/push-to-cf/push-to-cf.yml
    input_mapping:
      config: config-pr
      src-ci: src-pr
    params:
      APP_NAME: blockchain-stats
      APP_DOMAIN: {{app-domain}}
      BUILDPACK: java_buildpack
      CF_API: {{cf-api}}
      CF_USER: {{cf-user}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-pr-org}}
      CF_SPACE_PREFIX: ((cf-pr-space-prefix))
      CF_PATH: build/*.jar
  - task: frontend-acceptance-tests
    file: src-pr/ci/tasks/frontend-acceptance-tests/frontend-acceptance-tests.yml
    input_mapping:
      src: src-pr
      src-ci: src-pr  
    params:
      PROFILE: pr
      
- name: build-master
  plan:
  - get: src-master
    trigger: true
  - task: build
    file: src-master/ci/tasks/maven-package/maven-package.yml
    input_mapping:
      src: src-master
      src-ci: src-master
    params:
      TARGET_PATH: src/backend/target/*
      DOCKERFILE: src/Dockerfile
  - put: artifacts
    params:
      file: build/*.jar
  - put: docker-image-spring-boot-sample-blockchain
    params:
      build: build

- name: deploy-cf-staging
  plan:
  - get: config-staging
    trigger: true
  - get: src-master
    passed: ["build-master"]
  - get: artifacts
    trigger: true
    passed: ["build-master"]
  - task: push-to-cf
    file: src-master/ci/tasks/push-to-cf/push-to-cf.yml
    input_mapping:
      build: artifacts
      config: config-staging
      src-ci: src-master
    params:
      APP_NAME: blockchain-stats
      APP_HOSTNAME: staging-blockchain-stats
      APP_DOMAIN: {{app-domain}}
      DB_RECREATE: "true"
      DB_NAME: blockchain-db
      DB_SERVICE_NAME: cleardb
      DB_SERVICE_PLAN: spark
      BUILDPACK: java_buildpack
      CF_API: {{cf-api}}
      CF_USER: {{cf-user}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-staging-org}}
      CF_SPACE: {{cf-staging-space}}
      CF_PATH: build/*.jar
  - put: app-url
    params:
      file: app-url/app-url
        
- name: acceptance-tests-cf-staging
  plan:
  - get: src-master
    passed: ["deploy-cf-staging"]
  - get: artifacts
    passed: ["deploy-cf-staging"]
  - get: app-url
    passed: ["deploy-cf-staging"]
    trigger: true
  - task: frontend-acceptance-tests
    file: src-master/ci/tasks/frontend-acceptance-tests/frontend-acceptance-tests.yml
    input_mapping:
      src: src-master
      src-ci: src-master  
    params:
      PROFILE: staging

- name: deploy-cf-production
  plan:
  - get: config-production
    trigger: true
  - get: src-master
    passed: ["acceptance-tests-cf-staging"]
  - get: artifacts
    passed: ["acceptance-tests-cf-staging"]
  - task: push-to-cf
    file: src-master/ci/tasks/push-to-cf/push-to-cf.yml
    input_mapping:
      build: artifacts
      config: config-production
      src-ci: src-master
    params:
      APP_NAME: blockchain-stats
      APP_HOSTNAME: production-blockchain-stats
      APP_DOMAIN: {{app-domain}}
      DB_NAME: blockchain-db
      DB_SERVICE_NAME: {{db-service-name}}
      DB_SERVICE_PLAN: {{db-service-plan}}
      BUILDPACK: java_buildpack
      CF_API: {{cf-api}}
      CF_USER: {{cf-user}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-production-org}}
      CF_SPACE: {{cf-production-space}}
      CF_PATH: build/*.jar
  - put: app-url
    params:
      file: app-url/app-url
