---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: src-pr
  type: pull-request
  source:
    repo: {{github-repository}}
    access_token: {{github-access_token}}

jobs:
- name: validate-pull-request
  plan:
  - get: src-pr
    trigger: true
  - task: build
    file: src-pr/ci/tasks/maven-package/maven-package.yml
    input_mapping:
      src: src-pr
      ci: src-pr
  - task: push-to-cf
    file: src-pr/ci/tasks/push-to-cf/push-to-cf.yml
    input_mapping:
      src-ci: src-pr
      
    params:
      APP_NAME: blockchain-stats
      APP_HOSTNAME: blockchain-stats
      APP_DOMAIN: {{app-domain}}
      BUILDPACK: java_buildpack
      CF_API: {{cf-api}}
      CF_USER: {{cf-user}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-org}}
      CF_SPACE_PREFIX: ((cf-space-prefix))