---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk-slim

inputs:
- name: src
- name: src-ci
- name: app-url

run:
  path: src-ci/ci/tasks/backend-acceptance-tests/backend-acceptance-tests.sh
  
params:
  PROFILE: 